### ISSUE TITLE
How would I get my current page somewhere in the app?

### ISSUE THREAD

**Issue by michaelcuneo** [Hejtmus/svelte-fullpage#49]
How would I get my current page somewhere in the app?

**Comment by Hejtmus** [comment]
Hello,

currently svelte-fullpage doesn't have programmatic navigation with navigation indicator. So for now I would use [intersection observer](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API). Next version of this lib will feature programmatic navigation with its indicator (#47). If you have any proposal for managing navigation, I would appreciate your comment on that. At least some description of expected navigation usage will help me better design navigation management, than just guessing potential navigation requirements.

Best regards,
Filip.

**Comment by alexcloudstar** [comment]
Any updates on this? @Hejtmus

**Comment by Hejtmus** [comment]
> Any updates on this? @Hejtmus 

@alexcloudstar, yes, use controller interface, you can see example code on demo page in this repo. I'll have to document that this issue is resolved.

**Comment by alexcloudstar** [comment]
Thank you!

**Comment by alexcloudstar** [comment]
Maybe is me.. but I still don't understand how to do this. I don't have any Svelte experience, I'm a React guys, but looking to gather some experience in Svelte as well

**Comment by alexcloudstar** [comment]
Don't find any docs about indicators, programatic scroll etc.... can you help @Hejtmus ?

**Comment by Hejtmus** [comment]
> Maybe is me.. but I still don't understand how to do this. I don't have any Svelte experience, I'm a React guys, but looking to gather some experience in Svelte as well @Hejtmus

Sorry for just throwing project specific term at you, controller is interface for programmatic navigation and getting navigation info, it is Svelte store, which is basically object observable pattern.
[Here](https://github.com/Hejtmus/svelte-fullpage/blob/master/src/lib/stores.ts) you can see definition of controller, you can use these methods `previousPage`, `nextPage`, `toPage`, they do exactly what you think they do. If you want to get current section, you have to subscribe to that store.

But first of all, you need reference to controller:

```svelte
<Fullpage bind:controller={fullpageController}>
    ...
</Fullpage>
```
https://github.com/Hejtmus/svelte-fullpage/blob/cc161689d4392e4df6e12eb1dd719e89a88f88be/src/routes/%2Bpage.svelte#L29

Then you can subscribe current position:

```svelte
$: console.log(`Active section: ${$fullpageController}`)
```
https://github.com/Hejtmus/svelte-fullpage/blob/cc161689d4392e4df6e12eb1dd719e89a88f88be/src/routes/%2Bpage.svelte#L22C5-L22C60

Or call methods I mentioned.

**Comment by Hejtmus** [comment]
> Don't find any docs about indicators, programatic scroll etc.... can you help @Hejtmus ?

@alexcloudstar , to be fair, documentation of this project is poor, and I have to revamp it. 

I think [this issue](https://github.com/Hejtmus/svelte-fullpage/issues/47) could help you understand programmatic navigation.

You mentioned indicators, they are just simple buttons that observe current page, and if their index is equal to current page, they become filled, take a [look](https://github.com/Hejtmus/svelte-fullpage/blob/cc161689d4392e4df6e12eb1dd719e89a88f88be/src/lib/Indicator/Dot.svelte). When they are clicked, they propagate event, which will end up be handled by scrolling to desired coordinates.

If you need more documentation, please create new issue as it could be unrelated to topic of this one. Feel free to give feedback to documentation, request certain things to be explained, my look at this project is biased by work on it, thus your opinion is valued.
